AWSTemplateFormatVersion : '2010-09-09'
#Transform: AWS::Serverless-2016-10-31

Resources:
#  Invoker:
#    Type: AWS::Serverless::Function
#    Properties:
#      CodeUri: ./src
#      Environment:
#        StateMachineBucket: !Ref StateMachineBucket 
#        StateTable: !GetAtt [StateTable, Arn]
#      Handler: invoker.handler
#      MemorySize: 128
#      Runtime: "Python2.7"
#      Timeout: 300
#      Policies:
#      - AmazonS3FullAccess
#      - AmazonDynamoDBReadOnlyAccess

  StateMachineBucket:  
    Type: "AWS::S3::Bucket"
    Properties: {}
  
  StateTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
      - AttributeName: state_machine_id
        AttributeType: S
      - AttributeName: state_id
        AttributeType: S
      KeySchema:
      - AttributeName: state_machine_id
        KeyType: HASH
      - AttributeName: state_id
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      StreamSpecification:
        StreamViewSpecification: NEW_AND_OLD_IMAGES
  
#  StateRole:
#    Type: AWS::IAM::Role
#    Properties:
#      Policies:
#      - AmazonS3FullAccess
#      - AmazonDynamoDBReadOnlyAccess
  
